### ISSUE TITLE
TreeUI error on modify

### ISSUE THREAD

**Issue by ChargeIn** [ChargeIn/RestTester#8]
java.lang.Throwable: TreeUI should be accessed only from EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.tree.ui.DefaultTreeUI.isValid(DefaultTreeUI.java:216)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRowForPath(DefaultTreeUI.java:766)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateLeadSelectionRow(BasicTreeUI.java:2847)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:2013)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateLayoutCacheExpandedNodes(BasicTreeUI.java:1979)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateLayoutCacheExpandedNodesIfNecessary(BasicTreeUI.java:1986)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.configureLayoutCache(BasicTreeUI.java:2132)
	at com.intellij.ui.tree.ui.DefaultTreeUI.configureLayoutCache(DefaultTreeUI.java:454)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.completeUIInstall(BasicTreeUI.java:840)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.installUI(BasicTreeUI.java:800)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:733)
	at java.desktop/javax.swing.JTree.setUI(JTree.java:760)
	at com.intellij.ui.treeStructure.Tree.setUI(Tree.java:128)
	at java.desktop/javax.swing.JTree.updateUI(JTree.java:781)
	at com.flop.resttester.requesttree.RequestTreeHandler.updateTree(RequestTreeHandler.java:276)
	at com.flop.resttester.RestTesterWindow$1.onChange(RestTesterWindow.java:69)
	at com.flop.resttester.request.RequestWindow.changeCallback(RequestWindow.java:233)
	at com.flop.resttester.utils.Debouncer$1.run(Debouncer.java:40)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)

**Comment by ChargeIn** [comment]
Fixed with 1.1.1
